baseURL                = 'https://www.robsoncassiano.software/'
defaultContentLanguage = "pt-br"
enableRobotsTXT        = true
languageCode           = 'pt-BR'
title                  = 'On the shoulders of giants'
theme                  = 'anatole'

# Google Analytics
#googleAnalytics = "UA-123-45"
