title                = "Robson Cassiano Blog"
author               = "Robson Cassiano"
profilePicture       = "images/robson-cassiano-profile.webp"
relatedPosts = true
numberOfRelatedPosts = 2

[[socialIcons]]
icon  = "fab fa-linkedin"
title = "Linkedin"
url   = "https://www.linkedin.com/in/robsoncassiano-software"

[[socialIcons]]
icon  = "fas fa-envelope"
title = "e-mail"
url   = "falecom@robsoncassiano.software"

[[socialIcons]]
icon  = "fa-brands fa-instagram"
title = "Instagram"
url   = "https://www.instagram.com/robsoncassiano.software/"

[[socialIcons]]
icon  = "fa-brands fa-youtube"
title = "Youtube"
url   = "https://www.youtube.com/@RobsonCassianoSoftware"

[[socialIcons]]
icon  = "fa-brands fa-twitter"
title = "X"
url   = "https://x.com/RobsonDev"