baseURL      = 'https://www.robsoncassiano.software/'
languageCode = 'pt-BR'
DefaultContentLanguage = "pt-BR"
title        = 'Robson Cassiano'
theme        = 'anatole'

[params]
title          = "Robson Cassiano"
author         = "Robson Cassiano"
profilePicture = "images/robson-cassiano-profile.webp"

[[params.socialIcons]]
icon  = "fab fa-linkedin"
title = "Linkedin"
url   = "https://linkedin.com/robson-cassiano-software"

[[params.socialIcons]]
icon  = "fas fa-envelope"
title = "e-mail"
url   = "robson.cassiano@pm.me"

[Languages.pt-BR]
contentDir = "content/brazilian"
description  = "Sobre os ombros de gigantes"
LanguageName = "BR"
weight       = 1

[Languages.en]
contentDir = "content/english"
description  = "On the shoulders of giants"
LanguageName = "US"
weight       = 2

[[Languages.en.menu.main]]
identifier = "home"
name       = "Home"
url        = "/en/"
weight     = 100

[[Languages.en.menu.main]]
identifier = "posts"
name       = "Articles"
url        = "/en/articles/"
weight     = 200

[[Languages.en.menu.main]]
identifier = "courses"
name       = "Courses"
url        = "/en/courses/"
weight     = 300

[[Languages.en.menu.main]]
identifier = "about"
name       = "About"
url        = "/en/about/"
weight     = 400

[[Languages.pt-BR.menu.main]]
identifier = "home"
name       = "Home"
url        = "/pt-BR/"
weight     = 100

[[Languages.pt-BR.menu.main]]
identifier = "articles"
name       = "Artigos"
url        = "/pt-BR/articles/"
weight     = 200

[[Languages.pt-BR.menu.main]]
identifier = "courses"
name       = "Cursos"
url        = "/pt-BR/cursos/"
weight     = 300

[[Languages.pt-BR.menu.main]]
identifier = "about"
name       = "Sobre mim"
url        = "/pt-BR/about/"
weight     = 400
